version: "3"
services:
  aeroporto_FCCPD:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=aeroporto123
      - POSTGRES_DATABASE=aeroporto

#docker run --name aeroporto_FCCPD -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=aeroporto123 -e POSTGRES_DATABASE=aeroporto -p 5432:5432 bitnami/postgresql:latest