version: "3.8"
services:
  aeroporto_db:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=aeroporto123
      - POSTGRES_DATABASE=aeroporto

  aeroporto_app:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://docker:aeroporto123@aeroporto_db:5432/aeroporto
    depends_on:
      - aeroporto_db

#docker run --name aeroporto_FCCPD -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=aeroporto123 -e POSTGRES_DATABASE=aeroporto -p 5432:5432 bitnami/postgresql:latest