version: '3'
services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 20s; streamlit run ./main.py"
    depends_on:
      - mysql
    ports:
      - "8501:8501"
  mysql:
    build: ./sql/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
